//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M17AB_TrabalhoModelo_2022_23.Admin.Utilizadores
{


    public partial class bloquearutilizador
    {
    }
}
